### ISSUE TITLE
Feature: Add Parent Fault diagnostic views to TUI

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/simple-toshi-ui#174]
**AS SRM team**

**we want** to select views for Parent Faults within a new Tab on the FlipChart

**so that** we're able to examine effects of the new  Paleo Site constraints.

NB there are more than 600 Parent Faults, so its not feasible to look at all these. For first cut we could:
 - provide some preselected views based on fault in Named Faults list
 - Provide a search-assisted selector control.
 - support vertical paging

**Done When:**
 - [x] user can see a new Parent Faults tab (Crustal Solutions only)
 - [x] user can multi-select from list of (~8) parent fault views (CC to provide path & names)
 - [x] user can select one item from all the Parent Fault names (need autocomplete)
 - [x] display Parent Fault name top of tab

**View Data:**
 - [parent_fault_names.txt](https://github.com/GNS-Science/simple-toshi-ui/files/7605201/parent_fault_names.txt)
 - [parent_views.txt](https://github.com/GNS-Science/simple-toshi-ui/files/7605289/parent_views.txt)

 - example TEST resource: http://nzshm22-static-reports-test.s3-website-ap-southeast-2.amazonaws.com/opensha/DATA/SW52ZXJzaW9uU29sdXRpb246Mjk2MS4wREtva2Q=/solution_report/parent_sect_pages/Paritu_West/resources/sect_along_strike_mo_b.png
 -  - example PROD resource: http://nzshm22-static-reports.s3-website-ap-southeast-2.amazonaws.com/opensha/DATA/../solution_report/parent_sect_pages/Paritu_West/resources/sect_along_strike_mo_b.png

**Comment by 0qy** [comment]
use Pritu_West and R2VuZXJhbFRhc2s6MTQxMU00ckNZ to test this feature with Test DB
