### ISSUE TITLE
Feature: clear Parent Faults dropdown

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/simple-toshi-ui#178]
As TUI owner I want to make it easier to clear the Parent Faults selection. User currently has to click "x" twice to clear the selection (first click causes the menu to auto-select first entry in drop down list, second click clears completely).

**Done When**

- [ ] It no longer requires clicking the "x" on the Parent Faults selection twice to completely clear the entry

**Comment by 0qy** [comment]
I have fixed this in the MUI update branch
