### ISSUE TITLE
Issue: "Cannot show reports" alert appears when filtering

### ISSUE THREAD

**Issue by benjamineac** [GNS-Science/simple-toshi-ui#205]
Every time I filter the general task's child tasks if the filtered amount is above the report limit the alert appears. 
The alert should only pop up when I have clicked the 'show reports' button.

**Comment by chrisbc** [comment]
@benjamineac OK we need to make a call on that behaviour -  @chrisdicaprio can you pls decide this one ? :)

**Comment by chrisdicaprio** [comment]
I prefer the behavior described by @benjamineac
