### ISSUE TITLE
Problems fighting Typescript checking and prettier rules with D3 examples

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/simple-toshi-ui#24]
This is more of a TS noobs feedback comment than a TODO. But I wanted to capture my experience whilst still fresh.

I tried to explore a couple of new features and ran into many frustrating compile errors in two areas:

 1. **prettier** is picky - too picky, and refuses to deal with with D3-style **dot continuations** well. eg 
    ```    //Add line 1, supraSeismo
    svg.append('path')
      .datum(data0)
      .attr('fill', 'none')
      .attr('stroke', 'steelblue')
      .attr('stroke-width', 3)
      .attr('d', d3.line()
          .x((d) => x(d.mag))
          .y((d) => y(d.rate))
      );```

~~I couldn't figure out how to calm it down or disable it (to give me some more freedom to experiment).~~
OK I found `// prettier-ignore`

 2. see below

**Comment by chrisbc** [comment]
Hi @wooneh if you are able to take a look at this I'd be grateful....

I have an [almost working typescript version here](https://github.com/GNS-Science/simple-toshi-ui/tree/preview/19_mfd_histograms) . The line I haven't been able to resolve is[ commented out here](https://github.com/GNS-Science/simple-toshi-ui/blob/07631bfbb0e36184746886e15f6695a1f224eb58/src/components/PreviewLineMFD.tsx#L45).

I also have a [working javascript-only version here](https://github.com/chrisbc/explore-d3-react). 

The code is almost identical,  and the two routes:
- http://localhost:3000/PreviewMFD
- http://localhost:3000/PreviewLIneMFD

should render the same in both. Right now only the first one does that

**Comment by wooneh** [comment]
Hi Chris, no worries, does this work to add the data type to d3.line?

```
svg
  .append<SVGPathElement>('path')
  .datum(data)
  .attr('fill', 'none')
  .attr('stroke', 'steelblue')
  .attr('stroke-width', 1.5)
  .attr('d', d3.line<IMagRate>()
    .x((d) => x(d.mag))
    .y((d) => y(d.rate))
);
```

**Comment by chrisbc** [comment]
!&& Yes !! I'm pretty sure I tried this already  (hence the IMagRate that I defined) but it' seems that's all it took! Thanks @wooneh  !
