### ISSUE TITLE
Feature: add inversion progress to GT flip chart 

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/simple-toshi-ui#246]
We want to see the inversion progress figure added to the GT flip chart under the GENERAL tab:

- image file name is `sa_progress_perturb_vs_iters.png`
- example http://nzshm22-static-reports-test.s3-website-ap-southeast-2.amazonaws.com/opensha/DATA/SW52ZXJzaW9uU29sdXRpb246Mjc0NS4wbkpuSkg=/solution_report/resources/sa_progress_perturb_vs_iters.png
- name to show in list: `Perturbations & Non-Zero Rates`

**Comment by chrisbc** [comment]
closed by #247
