### ISSUE TITLE
Feature: add data table to SOLUTION ANALYSIS tab

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/simple-toshi-ui#257]
As a user I want to be able to click a button to have a table of the query results displayed below the map. The table columns should be (in order):
* Subsection Name (`fault_name`)
* Max Magnitude (`magnitude.max`)
* Min Magnitude (`magnitude.min`)
* Max Annual Rate (`annual_rate.max`)
* Min Annual Rate (`annual_rate.min`)
* Slip Rate (`slip rate`)

The list above is formatted as:
* Column Header (`geojson property`)

The table should have the column headers as the first row

**Comment by chrisbc** [comment]
@chrisdicaprio those max/min values won't be available from the current API. For that we'll need a new API feature. Suggest that for the first table you just show whats there in the geojson now. I'll attach an example below ...

**Comment by chrisdicaprio** [comment]
Change the text on the button to read "HIDE TABLE" when the table is showing to make it more intuitive to toggle on and off.
