### ISSUE TITLE
Feature: Regionalized MFD Plot

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/simple-toshi-ui#275]
As a user I want to be able to view the MFDs by region and select which curves are shown in the `MFD PLOT` view of an individual `InversionSolution`.

**NB**: this ticket is not for the dynamic MFD plot in the `GeneralTask` flipchart view.

The API will provide a `"table_type": "MFD_CURVES_V2"` that has the following curves (if V2 of the `MFD_CURVES` is not available then the old version `MFD_CURVES` will be provided and should be plotted as they are now):

```
- totalGR_MFD_<region>
- trulyOffFault_MFD_<region>
- subSeismoOnFaul_MFD_<region>
- supraSeismoOnFault_MFD_<region>
- solution_MFD_<region>
```
where `<region>` is `TVZ`, `SansTVZ`, and `both`

There are two dropdown menus above the MFD plot: `Region` and `MFD Curves`. 

`Region` only allows a single choice from:
- `TVZ`
- `SansTVZ`
- `both`

`MFD Curves` allows multiple choices from:
- `total GR`
- `truly off fault`
- `sub-seismo on fault`
- `supra-seismo on fault`
- `solution`

The curves plotted are then selected based on the region and particular curve type requested. 

The title of the plot should say `MFD for <region>`
The legend of the plot should have the selected names from the `MFD Curves` menu

![image](https://user-images.githubusercontent.com/91439467/154888157-2ade6878-4256-415c-bc21-4365a7a94e3d.png)

**Comment by chrisbc** [comment]
@0qy Actual series names...

```totalTargetGR.all
InversionTargetMFDs.totalTargetGR_SansTVZ
InversionTargetMFDs.totalTargetGR_TVZ
trulyOffFaultMFD.all
InversionTargetMFDs.trulyOffFaultMFD_SansTVZ.
InversionTargetMFDs.trulyOffFaultMFD_TVZ.
targetOnFaultSupraSeisMFD.all
InversionTargetMFDs.targetOnFaultSupraSeisMFD_SansTVZ
InversionTargetMFDs.targetOnFaultSupraSeisMFD_TVZ
totalSubSeismoOnFaultMFD.all
InversionTargetMFDs.totalSubSeismoOnFaultMFD_SansTVZ.
InversionTargetMFDs.totalSubSeismoOnFaultMFD_TVZ.
solutionMFD
```

and I suggest that you pre-process these and :
 - remove the prefix `InversionTargetMFDs.`
 - remove the suffix `.`
 
that way they'll look a lot cleaner in the UI, while still being unique.

And FYI tere'll be another ticket later this week to add two more series:
 - `solutionMFD_SansTVZ`
 - `solutionMFD_TVZ`
