### ISSUE TITLE
Feature: add paleo fit plot to GT report

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/simple-toshi-ui#286]
We want `GENERAL` tab in GT flip-chart to have options for:
- `paleo_rate_scatter.png` ["Paleo Fit"]
- `misift_progress_MAD.png` ["Misfit Progress"]
- `misift_progress_weights.png` ["Re-Weighting"]

**Comment by benjamineac** [comment]
is misift_progress_MAD.png meant to be spelled misfit_progress_MAD.png? save with weights

**Comment by benjamineac** [comment]
https://github.com/GNS-Science/simple-toshi-ui/pull/288
