### ISSUE TITLE
Feature: display information for ScaledInversionSolution

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/simple-toshi-ui#326]
When viewing a ScaledInversionSolution in TUI I want to see the information and meta data. 

Note a  ScaledInversionSolution looks almost identical to an InversionSolution. Differences are...

 - `source_solution` attribute returns the IS from which SIS was derived
 - in `meta` you'll see a {'k':'scale', 'v':int} item

Done When: 
- [ ] Have Scaled Inversion Solutions page wroking at link `/ScaledInversionSolution/${id}`
- [ ] User can view Solution Diagnostic view
- [ ] Add this link to `App.tsx` routing
- [ ] Add this link to `AutomationTask` file table

**Comment by chrisbc** [comment]
API example (TEST)...

**Comment by chrisdicaprio** [comment]
for testing: GT ID in TEST R2VuZXJhbFRhc2s6MTAwMTg3
