### ISSUE TITLE
Feature: view for InversionSolutionNrml objects

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/simple-toshi-ui#345]
This view represents specific type of file - a zip archive containing the openquake source files built from a specific Inversion Solution (and or Scaled/Averaged InversionsSolution.

So is has an extra field that File does not: 

 - [x] Same as File: name, size, download etc
 - [x] display the InversionSolution ID as a navlink (and derive the Type from the ID)
 - [ ] Find a valid object links to new route /InversionSolutionNrml/{ID}
       e.g. `SW52ZXJzaW9uU29sdXRpb25Ocm1sOjEwMDM0OQ==`

### from API Schema docs...

**InversionSolutionNrml** archive file

This is a zip archive containing two XML source files that have been converted from the source_solution

NB any arguments used to generate this object should be captured as in meta field

**Comment by chrisdicaprio** [comment]
Add find support
